
Flowpack:
  Monolog:
    logger:
      securityLogger:
        handler:
          streamHandler:
            arguments:
              - '%FLOW_PATH_DATA%Logs/Security_Testing.log'
      sqlLogger:
        handler:
          streamHandler:
            arguments:
              - '%FLOW_PATH_DATA%Logs/Query_Testing.log'
Neos:
  Flow:
    log:
      systemLogger:
        backendOptions:
          configuration:
            handler:
              streamHandler:
                arguments:
                  - '%FLOW_PATH_DATA%Logs/System_Testing.log'
