
Flowpack:
  Monolog:
    handler:
      defaultHandler: null
      defaultSecurityLogHandler:
        className: Monolog\Handler\StreamHandler
        position: 100
        arguments:
          0: '%FLOW_PATH_DATA%Logs/Security.log'
      defaultQueryLogHandler:
        className: Monolog\Handler\StreamHandler
        position: 100
        arguments:
          0: '%FLOW_PATH_DATA%Logs/Query.log'
    logger:
      default:
        handler:
          streamHandler:
            className: Monolog\Handler\StreamHandler
            position: 100
            arguments:
              0: '%FLOW_PATH_DATA%Logs/Default.log'
      securityLogger:
        handler:
          streamHandler:
            className: Monolog\Handler\StreamHandler
            position: 100
            arguments:
              0: '%FLOW_PATH_DATA%Logs/Security.log'
      sqlLogger:
        handler:
          streamHandler:
            className: Monolog\Handler\StreamHandler
            position: 100
            arguments:
              0: '%FLOW_PATH_DATA%Logs/Query.log'
Neos:
  Flow:
    log:
      systemLogger:
        backend: Flowpack\Monolog\FlowBackendFacade
        backendOptions:
          identifier: systemLogger
          configuration:
            handler:
              streamHandler:
                className: Monolog\Handler\StreamHandler
                position: 100
                arguments:
                  0: '%FLOW_PATH_DATA%Logs/System.log'
      securityLogger:
        backend: Flowpack\Monolog\FlowBackendFacade
        backendOptions:
          identifier: securityLogger
      sqlLogger:
        backend: Flowpack\Monolog\FlowBackendFacade
        backendOptions:
          identifier: sqlLogger
